# This workflow runs the download_youthmappers.py script to access the OSMTeams API and 
# download all of the YouthMappers user info

name: Download YouthMappers Org from OSMTeams

on:
  schedule:
    - cron: "0 10 * * 5"

  workflow_dispatch:

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas
    - name: Download YouthMappers Data
      env:
        OSM_TEAMS_ACCESS_TOKEN: ${{ secrets.OSM_TEAMS_ACCESS_TOKEN }}
        DEBUG: False
      run: |
        python3 download_youthmappers.py        
    - name: Set Datestamp for file suffix
      run: |
        echo "DATESTAMP=$(date +"%Y-%m-%d")" >> ${GITHUB_ENV}
    - name: Upload Chapters to Google Drive
      uses: adityak74/google-drive-upload-git-action@main
      with:
        credentials: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
        filename: chapters.csv
        folderId: 1p6JeBvbsziMiBefCNet_q3nj9GvQWMnb
        name: chapters_${{env.DATESTAMP}}.csv
        overwrite: True
    - name: Upload YouthMappers to Google Drive
      uses: adityak74/google-drive-upload-git-action@main
      with:
        credentials: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
        filename: youthmappers.csv
        folderId: 1p6JeBvbsziMiBefCNet_q3nj9GvQWMnb
        name: youthmappers_${{env.DATESTAMP}}.csv
        overwrite: True
    - name: Upload members.json to Google Drive
      uses: adityak74/google-drive-upload-git-action@main
      with:
        credentials: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
        filename: members.json
        folderId: 1p6JeBvbsziMiBefCNet_q3nj9GvQWMnb
        overwrite: True
    - name: Upload chapters.json to Google Drive
      uses: adityak74/google-drive-upload-git-action@main
      with:
        credentials: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
        filename: chapters.json
        folderId: 1p6JeBvbsziMiBefCNet_q3nj9GvQWMnb
        overwrite: True
